language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip3 install -r requirements.txt
  - pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

script:
  - python3 -m main --no-cuda --ci
  - python3 -m evaluate --no-cuda --ci
